baseURL = 'https://www.mjcmorlaix.com'
locale = 'fr-fr'
defaultContentLanguage = "fr"
title = 'MJC Morlaix'
theme = 'mjc-morlaix'
copyright = '© MJC Morlaix'
summaryLength = '20'
[module]
[[module.mounts]]
  source = 'assets/medias'
  target = 'static/medias'

