baseURL = 'https://62bd7a908eca53730ee5d258--stunning-meringue-5e3b4f.netlify.app/'
languageCode = 'en-us'
defaultContentLanguage = "fr"
title = 'MJC Morlaix'
theme = 'mjc-morlaix'
copyright = '2022 © MJC Morlaix'
summaryLength = '20'

