backend:
  name: git-gateway
  branch: main

locale: 'fr'

media_folder: assets/medias 
public_folder: ../medias 

publish_mode: editorial_workflow

collections:
  - name: "accueil"
    label: "Accueil"
    editor: 
      preview: false
    files: 
      - name: "Accueil"
        label: "accueil"
        file: "content/_index.md"
        create: false
        fields: 
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
  - name: "actu"
    label: "Actualités"
    editor: 
      preview: false
    folder: "content/actu"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image d'accroche", name: "cover", widget: "image" }
      - { label: "Date et heure", name: "event_time", widget: "datetime", default: "", time_format: "HH:mm", picker_utc: false }
      - { label: "Lieu", name: "lieu", widget: "string" }
      - { label: "Prix", name: "prix_plein", widget: "number", min: 1 }
      - { label: "Prix Adhérent·e", name: "prix_abonné", widget: "number", min: 1 }
      - { label: "Contenu", name: "body", widget: "markdown" }
  - name: "trockson"
    label: "Trockson"
    editor: 
      preview: false
    folder: "content/trockson"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields: 
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image d'accroche", name: "cover", widget: "image" }
      - { label: "Date et heure", name: "event_time", widget: "datetime", default: "", time_format: "HH:mm", picker_utc: false }
      - { label: "Lieu", name: "lieu", widget: "string" }
      - { label: "Prix", name: "prix_plein", widget: "number", min: 1 }
      - { label: "Prix Adhérent·e", name: "prix_abonné", widget: "number", min: 1 }
      - { label: "Contenu", name: "body", widget: "markdown" }
  - name: "agenda"
    label: "Agenda"
    editor: 
      preview: false
    folder: "content/agenda"
    create: true
    extension: "md"
    fields: 
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image d'accroche", name: "cover", widget: "image" }
      - { label: "Date et heure", name: "event_time", widget: "datetime", default: "", time_format: "HH:mm", picker_utc: false }
      - { label: "Lieu", name: "lieu", widget: "string" }
      - { label: "Première partie", name: "first", widget: "string", required: false }   
      - { label: "Prix", name: "prix_plein", widget: "number", min: 1 }
      - { label: "Prix Adhérent·e", name: "prix_abonné", widget: "number", min: 1 }
      - { label: "Contenu", name: "body", widget: "markdown" }
  - name: "podcast"
    label: "Podcasts"
    editor: 
      preview: false
    folder: "content/podcasts"
    slug: "{{slug}}"
    extension: "md"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Pictogramme", name: "picto", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Auteur", name: "auteur", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Durée", name: "durée", widget: "string" }
      - { label: "Audio", name: "audio", widget: "file" }
  - name: "activites"
    label: "Activités"
    editor: 
      preview: false
    folder: "content/activites"
    slug: "{{slug}}"
    extension: "md"
    create: true
    fields: 
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Pictogramme", name: "picto", widget: "image" }
      - { label: "Public", name: "public", widget: "select", multiple: true, min: 1, max: 3, options: ["enfants", "adolescents", "adultes"] }
      - { label: "Animateur·ice", name: "anim", widget: "string" }
      - { label: "Prix", name: "price", widget: "string" }
      - { label: "Date de début", name: "starting_date", widget: "datetime" }
      - { label: "Créneau(x)", name: "creneau", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "documents"
    label: "Documents"
    editor: 
      preview: false
    folder: "content/documents"
    slug: "{{slug}}"
    extension: "md"
    create: true
    fields: 
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Format", name: "public", widget: "select", multiple: false, options: ["pdf", "word", "odt"] }
      - { label: "Pictogramme", name: "picto", widget: "image" }
      - { label: "Saison", name: "saison", widget: "string", required: false } 
      - { label: "Fichier", name: "Fichier", widget: "file" }
  - name: "legals"
    label: "Mentions Légales"
    editor: 
      preview: false
    files:
      - name: "legals"
        label: "Mentions Legales"
        file: "content/mentions-legales.md"
        create: false
        fields: 
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
